CHAR_MAX_LENGTH = 150
MIN_VALUE = 1
INN_ORGANIZATION_LENGTH = 10
INN_INDIVIDUAL_LENGTH = 12
MAX_INN_LENGTH = max(INN_ORGANIZATION_LENGTH, INN_INDIVIDUAL_LENGTH)
MIN_INN_LENGTH = min(INN_ORGANIZATION_LENGTH, INN_INDIVIDUAL_LENGTH)
DEFAULT_BALANCE = 0
