[tool.black]
line-length = 79
skip-string-normalization = 1
target-version = ['py39']

[tool.isort]
py_version = 39
src_paths = ['payment', 'api', 'payment_system']
profile = 'black'
skip = ['migrations', 'venv', ]
line_length = 79