# Generated by Django 4.2.17 on 2025-06-01 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'inn',
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='ИНН должен содержать либо 10, либо 12 цифр',
                                regex='^(?:\\d{10}|\\d{12})$',
                            )
                        ],
                        verbose_name='ИНН',
                    ),
                ),
                (
                    'balance',
                    models.BigIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='баланс',
                    ),
                ),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('inn',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'operation_id',
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name='идентификатор',
                    ),
                ),
                (
                    'amount',
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='Сумма транзакции',
                    ),
                ),
                ('document_number', models.CharField(max_length=150)),
                (
                    'document_date',
                    models.DateTimeField(
                        verbose_name='дата создания документа'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата добавления в бд'
                    ),
                ),
                (
                    'payer_inn',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='payment.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ('-document_date',),
            },
        ),
    ]
