# Generated by Django 4.2.17 on 2025-06-01 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='balance',
            field=models.BigIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='баланс',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payer_inn',
            field=models.CharField(
                max_length=12,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        message='ИНН должен содержать либо 10, либо 12 цифр',
                        regex='^(?:\\d{10}|\\d{12})$',
                    )
                ],
                verbose_name='ИНН',
            ),
        ),
    ]
