# Generated by Django 4.2.17 on 2025-06-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_organization_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={
                'ordering': ('inn',),
                'verbose_name': 'организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='payer_inn',
            new_name='inn',
        ),
    ]
