# Generated by Django 4.2.17 on 2025-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payer_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(verbose_name='Сумма транзакции'),
        ),
    ]
