# Generated by Django 4.2.17 on 2025-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='баланс'),
        ),
    ]
