from payment import consts

CHAR_MAX_LENGTH = consts.CHAR_MAX_LENGTH
MIN_VALUE = consts.MIN_VALUE
INN_ORGANIZATION_LENGTH = consts.INN_ORGANIZATION_LENGTH
INN_INDIVIDUAL_LENGTH = consts.INN_INDIVIDUAL_LENGTH
MAX_INN_LENGTH = max(INN_ORGANIZATION_LENGTH, INN_INDIVIDUAL_LENGTH)
MIN_INN_LENGTH = min(INN_ORGANIZATION_LENGTH, INN_INDIVIDUAL_LENGTH)

